version: '3'

services:
  mysql-wordpress:
    container_name: mysql-wordpress
    image: mysql:5
    restart: always
    volumes:
      - ${WP_DIR}/sql_data:/var/lib/mysql
      - ${WP_DIR}/initdb.d:/docker-entrypoint-initdb.d
    networks:
      default:
        ipv4_address: ${MYSQL_WP_IP}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_WP_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_WP_USER}
      MYSQL_PASSWORD: ${MYSQL_WP_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_WP_DATABASE}

  wordpress:
    container_name: wordpress
    image: wordpress:php7.0
    restart: always
    ports:
      - "${WP_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${WP_IP}
    volumes:
      - ${WP_DIR}/splc:/var/www/html
    depends_on:
      - mysql-wordpress
    links:
      - mysql-wordpress:mysql
    environment:
      WORDPRESS_DB_USER: ${MYSQL_WP_USER} 
      WORDPRESS_DB_PASSWORD: ${MYSQL_WP_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_WP_DATABASE}

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  flask:
    container_name: flask
    image: flask
    restart: always
    ports:
      - "${FLASK_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${FLASK_IP}
    volumes:
      - ${FLASK_DIR}:/app

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  cabina_votaciones:
    container_name: cabina_votaciones
    image: egc/node
    restart: always
    ports:
      - "${CABINA_EXPOSED_PORT}:8080"
    networks:
      default:
        ipv4_address: ${CABINA_IP}
    volumes:
      - ${CABINA_DIR}:/app

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  cabina_votaciones_telegram:
    container_name: cabina_votaciones_telegram
    image: egc/maven
    volumes:
      - ${TELEGRAM_DIR}:/app
    working_dir: /app/basicBot

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  recuento_votos:
    container_name: recuento_votos
    image: composer
    restart: always
    ports:
      - "${RECUENTO_EXPOSED_PORT}:8000"
    networks:
      default:
        ipv4_address: ${RECUENTO_IP}
    volumes:
      - ${RECUENTO_DIR}:/app
    working_dir: /app
    command: ["bash", "-c", "composer install && php -S localhost:8000 -t public"]

networks:
  default:
    external:
      name: ${NET_NAME}
