version: '3'

services:
  mysql-wordpress:
    container_name: mysql-wordpress
    image: mysql:5
    restart: always
    volumes:
      - ${WP_DIR}/sql_data:/var/lib/mysql
      - ${WP_DIR}/initdb.d:/docker-entrypoint-initdb.d
    networks:
      default:
        ipv4_address: ${MYSQL_WP_IP}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_WP_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_WP_USER}
      MYSQL_PASSWORD: ${MYSQL_WP_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_WP_DATABASE}

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  mysql-voting:
    container_name: mysql-voting
    image: egc/mysql
    restart: always
    ports:
      - "${MYSQL_VT_EXPOSED_PORT}:3306"
    networks:
      default:
        ipv4_address: ${MYSQL_VT_IP}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_VT_ROOT_PASSWORD}

  wordpress:
    container_name: wordpress
    image: wordpress:php7.0
    restart: always
    ports:
      - "${WP_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${WP_IP}
    volumes:
      - ${WP_DIR}/splc:/var/www/html
    depends_on:
      - mysql-wordpress
    links:
      - mysql-wordpress:mysql
    environment:
      WORDPRESS_DB_USER: ${MYSQL_WP_USER} 
      WORDPRESS_DB_PASSWORD: ${MYSQL_WP_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_WP_DATABASE}

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  portal-votaciones:
    container_name: portal-votaciones
    image: egc/portal
    restart: always
    ports:
      - "${FLASK_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${FLASK_IP}

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  autenticacion:
    container_name: autenticacion
    image: egc/django2
    restart: always
    ports:
      - "${AUT_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${AUT_IP}
    volumes:
      - ${AUT_DIR}:/app

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  adm_censos:
    container_name: adm_censos
    image: egc/django3
    restart: always
    ports:
      - "${ADM_CENSOS_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${ADM_CENSOS_IP}
    volumes:
      - ${ADM_CENSOS_DIR}:/app

  adm_votaciones:
    container_name: adm_votaciones
    image: egc/tomcat
    restart: always
    ports:
      - "${ADM_VOT_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${ADM_VOT_IP}
    volumes:
      - ${ADM_VOT_DIR}:/usr/local/tomcat/webapps

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  almacen_votos:
    container_name: almacen_votos
    image: egc/almacen
    restart: always
    ports:
      - "${ALMACEN_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${ALMACEN_IP}
    volumes:
      - ${ALMACEN_DIR}:/app

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  cabina_votaciones:
    container_name: cabina_votaciones
    image: egc/node
    restart: always
    ports:
      - "${CABINA_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${CABINA_IP}
    volumes:
      - ${CABINA_DIR}:/app

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  cabina_votaciones_telegram:
    container_name: cabina_votaciones_telegram
    image: maven
    volumes:
      - ${TELEGRAM_DIR}:/app
    working_dir: /app/basicBot
    command: ["mvn", "clean", "install", "exec:java"]

# WARNING: USING CUSTOM IMAGE. COMPILE IMAGE FIRST.

  recuento_votos:
    container_name: recuento_votos
    image: composer
    restart: always
    ports:
      - "${RECUENTO_EXPOSED_PORT}:80"
    networks:
      default:
        ipv4_address: ${RECUENTO_IP}
    volumes:
      - ${RECUENTO_DIR}:/app
    working_dir: /app
    command: ["bash", "-c", "composer install && php -S localhost:80 -t public"]

networks:
  default:
    external:
      name: ${NET_NAME}
